version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.IdentityModel.Tokens
    versions:
    - 6.10.0
    - 6.10.1
    - 6.10.2
    - 6.8.0
    - 6.9.0
  - dependency-name: System.IdentityModel.Tokens.Jwt
    versions:
    - 6.10.0
    - 6.10.1
    - 6.10.2
    - 6.8.0
    - 6.9.0
  - dependency-name: Swashbuckle.AspNetCore
    versions:
    - 5.6.3
    - 6.0.0
    - 6.0.2
    - 6.0.4
    - 6.0.5
    - 6.0.6
    - 6.0.7
    - 6.1.0
    - 6.1.1
    - 6.1.2
  - dependency-name: Swashbuckle.AspNetCore.Swagger
    versions:
    - 5.6.3
    - 6.0.0
    - 6.0.2
    - 6.0.4
    - 6.0.5
    - 6.0.6
    - 6.0.7
    - 6.1.0
    - 6.1.1
    - 6.1.2
  - dependency-name: Microsoft.EntityFrameworkCore.SqlServer
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: StackExchange.Redis.Extensions.Newtonsoft
    versions:
    - 6.3.6
    - 6.4.3
    - 6.4.5
  - dependency-name: dotenv.net
    versions:
    - 2.1.3
  - dependency-name: Microsoft.VisualStudio.Web.CodeGeneration.Design
    versions:
    - 5.0.1
